### PR TITLE
Improve freeze timer expired check

### PR DESCRIPTION
**Pull request by 7ez**
all I can say is that it's not a mess anymore

### CODE REVIEW

**Comment by 7ez** [comment]
ok cool

**Review by tsunyoku — CHANGES_REQUESTED** [review]
next time don’t commit an unrelated change tho ty

**Comment by tsunyoku** [comment]
what i mwant to approve

**Review by tsunyoku — APPROVED** [review]

**Comment by tsunyoku** [comment]
nvm other change was pre-commit Bruh

**Comment by 7ez** [comment]
> next time don’t commit an unrelated change tho ty

wdym commit unrelated change

**Comment by tsunyoku** [comment]
> > next time don’t commit an unrelated change tho ty
> 
> wdym commit unrelated change

don’t worry PreCommit Skill Issue!

**Comment by 7ez** [comment]
> > > next time don’t commit an unrelated change tho ty
> > 
> > 
> > wdym commit unrelated change
> 
> don’t worry PreCommit Skill Issue!

XD

**Pull request merged**
